name: xsdba
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.12,<3.13
  - sphinx >=7.0.0
  - pandoc
  - sphinx-rtd-theme >=1.0
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinxcontrib-bibtex
  - sphinxcontrib-napoleon
  - typer >=0.12.3
  - nbsphinx
  - ipython
